# Generated by Django 4.1.7 on 2023-04-16 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="selected_users",
            field=models.ManyToManyField(
                blank=True, related_name="issued_coupons", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
