# Generated by Django 4.1.7 on 2023-03-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='is_updated',
        ),
    ]
