# Generated by Django 4.1.7 on 2023-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rating_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
