# Generated by Django 4.1.7 on 2023-04-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_remove_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingimage',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingImage',
        ),
    ]
