# Generated by Django 4.1.7 on 2023-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, help_text="discount percents off", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("on_delivery", "On Delivery"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="processing",
                max_length=15,
            ),
        ),
    ]
