# Generated by Django 4.1.7 on 2023-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.TextField(blank=True, null=True),
        ),
    ]
