# Generated by Django 4.1.7 on 2023-03-09 07:32

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=20), size=6
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.TextField(), size=4
            ),
        ),
    ]
