# Generated by Django 4.1.7 on 2023-03-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_colors_alter_product_sizes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="url",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
    ]
